import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getPairs } from '@/utils/getPairs';
import { TPair } from '@/types';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ pairs }: { pairs: TPair[] }) {

  return (
    <>
      <Head>
        <title>Forex App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {pairs.map(pair => {
          return <Link key={pair.id} href={`/pairs/${pair.id}`} ><button className={styles.button} >{pair.label}</button></Link>
        })}
      </main>
    </>
  )
}


export async function getStaticProps() {
  const pairs = await getPairs();
  return {
    props: {
      pairs
    }
  }
}